
export const ADD_KUT = 'ADD_KUT'
export const ADD_NEW_CZYNNOSC = 'ADD_NEW_CZYNNOSC'
export const ON_ADDING_KUT = 'ON_ADDING_KUT'
export const OPEN_KUT = 'OPEN_KUT'
export const ZAMYKANIE_KARTY = 'ZAMYKANIE_KARTY'
export const USUWANIE_KARTY = 'USUWANIE_KARTY'
export const ZAPISZ_AKRONIM = 'ZAPISZ_AKRONIM'
export const ZAPISZ_TYP = 'ZAPISZ_TYP'
export const USUN_TYP = 'USUN_TYP'
export const ANULOWANIE = 'ANULOWANIE'
export const NOWY_NUMER = 'NOWY_NUMER'
export const RESET = 'RESET'